### PR TITLE
fix web app detection

### PR DESCRIPTION
**Pull request by brixzen**
just simple fixing query_id not found in new telegram mini web app

### CODE REVIEW

**Comment by manzoorwanijk** [comment]
Thank you for the PR.

In which case can `query_id` be not present?

**Comment by brixzen** [comment]
> Thank you for the PR.
> 
> In which case can `query_id` be not present?

i just open my telegram webapp using telegram app direct link, and query_id not there.

**Comment by Volaheck** [comment]
We are really waiting for this fix :)

**Review by Volaheck — APPROVED** [review]

**Comment by manzoorwanijk** [comment]
Sorry for missing this. I'll work on it this weekend.

**Review by manzoorwanijk — APPROVED** [review]
Thank you for the fix.

**Comment by manzoorwanijk** [comment]
This change is now published.

**Pull request merged**
